name: Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  dpeloy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - name: Install dependencies
        id: install-deps
        run: npm install

      - name: Build
        id: build
        run: npm run build

      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
