name: Deploy to Vercel

on:
  push:
    branches:
      - master

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - name: Install Vercel CLI
        id: install-vercel
        run: npm install -g vercel@latest

      - name: Pull Vercel config
        id: pull-vercel-config
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        id: build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy App
        id: deploy-app
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
