name: Deploy to S3

on:
  push:
    branches:
      - stagins

env:
  AWS_S3_BUCKET_STATIC: upload-widget-web-static
  AWS_S3_BUCKET_CDN: upload-widget-web-cdn
  SOURCE_DIR: dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - name: Install dependencies
        id: install-deps
        run: npm install

      - name: Build
        id: build
        run: npm run build

      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync files to S3 Static
        id: sync-static
        run: |
          aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET_STATIC }} --delete

      - name: Sync files to S3 CDN
        id: sync-cdn
        run: |
          aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET_CDN }} --delete

      - name: Invalidate CDN cache
        id: invalidate-cdn
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID }} --paths "/*"
